server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /mesh/ {
        proxy_pass http://api:8000/mesh/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /profiles {
        proxy_pass http://api:8000/profiles;
    }

    location /healthz {
        return 200 'ok - bunker web vivant\n';
        add_header Content-Type text/plain;
    }

    location = /generate_204 { return 302 http://adopteunmesh.local/; }
    location = /gen_204 { return 302 http://adopteunmesh.local/; }
    location = /hotspot-detect.html { return 302 http://adopteunmesh.local/; }
    location = /ncsi.txt { return 302 http://adopteunmesh.local/; }
    location = /connecttest.txt { return 302 http://adopteunmesh.local/; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
